### PR TITLE
Add Python 3.4/5/6, drop 3.3 and 2.6 

### LINKED ISSUE #2: Add Python 3.[456], drop 2.6/3.3
I'll try to get around to this in the near-ish future.

### PR DESCRIPTION
**Pull request by jamadden**
Fixes #2

- Rename .txt -> .rst
- Universal wheels
- Modern tox.ini and .travis.yml
  - Add coverage environment and coveralls
  - 100% coverage
- Use zope.testrunner for the namespace path issue.

### CODE REVIEW

**Review by mgedmin — COMMENTED** [review]
LGTM.

**Comment by mgedmin** [comment]
Out of curiosity, which part of the diff implements the "Universal wheels" bit?

**Comment by jamadden** [comment]
> Out of curiosity, which part of the diff implements the "Universal wheels" bit?

The [addition of setup.cfg](https://github.com/zopefoundation/z3c.macro/pull/3/files#diff-380c6a8ebbbce17d55d50ef17d3cf906) with the right bit twiddled marks this project as suitable for universal wheels. No code actually changed to do that.

**Comment by jamadden** [comment]
Thank you!

Could we please get a PyPI release (or access) when convenient?

**Comment by mgedmin** [comment]
> The addition of setup.cfg with the right bit twiddled marks this project as suitable for universal wheels. No code actually changed to do that.

D'oh, how did I miss that?

> Could we please get a PyPI release (or access) when convenient?

You have access now.

**Comment by jamadden** [comment]
Thank you.

2.1.0 has been released to PyPI.

**Pull request merged**
